### ISSUE TITLE
Loop in RTL

### ISSUE THREAD

**Issue by rbarzic** [rbarzic/nanorv32#35]
Found by Xilinx Vivado :
 There is 1 combinational loop in the design. (HIGH)

U_NANORV32_PIL/U_CPU/U_PREFETCH_BUFFER_i_35/O
U_NANORV32_PIL/U_CPU/U_PREFETCH_BUFFER_i_1/I1
U_NANORV32_PIL/U_CPU/U_PREFETCH_BUFFER_i_1/O
U_NANORV32_PIL/U_CPU/U_FLOW_CTRL/data_access_cycle_INST_0/I0
U_NANORV32_PIL/U_CPU/U_FLOW_CTRL/data_access_cycle_INST_0/O
U_NANORV32_PIL/U_CPU/U_ALU_i_67/I0
U_NANORV32_PIL/U_CPU/U_ALU_i_67/O
U_NANORV32_PIL/U_CPU/U_ALU_i_65/I2
U_NANORV32_PIL/U_CPU/U_ALU_i_65/O
U_NANORV32_PIL/U_CPU/U_PREFETCH_BUFFER_i_35/I0
U_NANORV32_PIL/U_CPU/U_PREFETCH_BUFFER_i_35/O

**Comment by jeabre01** [comment]
Fix inside the master
